<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movies [
   <!ELEMENT movies (movie)>
   <!ELEMENT movie (title, director+, distributor, release, duration)>
   <!ELEMENT title (#PCDATA)>
   <!ELEMENT director (#PCDATA)>
   <!ELEMENT distributor (#PCDATA)>
   <!ELEMENT release (#PCDATA)>
   <!ELEMENT duration (#PCDATA)>
]>
<movies>
    <movie id = "1">
        <title>Resident Evil: The Final Chapter</title>
        <director>Paul W. S. Anderson</director>
        <distributor>Sony Pictures</distributor>
        <release>1/27/2017</release>
        <duration>107</duration>
    </movie>
    <movie id = "2">
        <title>The Kissing Booth</title>
        <director>Vince Marcello</director>
        <distributor>Netflix</distributor>
        <release>5/11/2018</release>
        <duration>110</duration>
    </movie>
    <movie id = "3">
        <title>Jiang Ziya</title>
        <director>Cheng Teng, Li Wei</director>
        <distributor>Beijing Enlight Pictures</distributor>
        <release>10/1/2020</release>
        <duration>110</duration>
    </movie>
</movies>
